//ex 11
SELECT PRIMEIRO_NOME,DATA_NACIMENTO FROM ALUNOS WHERE 
	PRIMEIRO_NOME IN((SELECT PRIMEIRO_NOME FROM ALUNOS WHERE PRIMEIRO_NOME ILIKE '% %'))

  
SELECT ID_ALUNO,ID_DICIPLINA,FALTAS FROM ALUNOS_DICIPLINA
	WHERE FALTAS > (SELECT AVG(FALTAS) FROM ALUNOS_DICIPLINA);


SELECT 
    TD.NOME 
FROM (
    SELECT 
        TIPO_DICIPLINA_ID, 
        COUNT(TIPO_DICIPLINA_ID) AS CONTA 
    FROM 
        DICIPLINA 
    GROUP BY 
        TIPO_DICIPLINA_ID
) AS LALA
JOIN 
    TIPO_DICIPLINA TD 
    ON TD.ID = LALA.TIPO_DICIPLINA_ID
WHERE 
    CONTA = (
        SELECT 
            MAX(CONTA) 
        FROM (
            SELECT 
                TIPO_DICIPLINA_ID, 
                COUNT(TIPO_DICIPLINA_ID) AS CONTA 
            FROM 
                DICIPLINA 
            GROUP BY 
                TIPO_DICIPLINA_ID
        ) AS LALLA
    );
 

SELECT 
    CONCAT(A.PRIMEIRO_NOME, ' ', A.SOBRENOME) AS NOME_COMPLETO,
    D.NOME AS NOME_DISCIPLINA,
    (AD.P1 + AD.P2) AS MEDIA,
    AD.FALTAS
FROM 
    ALUNOS AS A
INNER JOIN 
    ALUNOS_DISCIPLINA AS AD ON A.ID_ALUNOS = AD.ID_ALUNO
INNER JOIN 
    DISCIPLINAS AS D ON D.ID_DISCIPLINA = AD.ID_DISCIPLINA
WHERE
    AD.FALTAS < (SELECT AVG(FALTAS) FROM ALUNOS_DISCIPLINA)
AND
    (AD.P1 + AD.P2) > (SELECT AVG(P1 + P2) FROM ALUNOS_DISCIPLINA)
ORDER BY
    NOME_COMPLETO, NOME_DISCIPLINA;


SELECT 
    subquery.NOME_COMPLETO,
    COUNT(subquery.NOME_DISCIPLINA) AS DISCIPLINAS_APROVADAS
FROM (
    SELECT 
        A.PRIMEIRO_NOME || ' ' || A.SOBRENOME AS NOME_COMPLETO,
        D.NOME AS NOME_DISCIPLINA,
        (AD.P1 + AD.P2) AS MEDIA,
        AD.FALTAS
    FROM 
        ALUNOS AS A
    INNER JOIN 
        ALUNOS_DISCIPLINA AS AD ON A.ID_ALUNOS = AD.ID_ALUNO
    INNER JOIN 
        DISCIPLINAS AS D ON D.ID_DISCIPLINA = AD.ID_DISCIPLINA
    WHERE
        AD.FALTAS < (SELECT AVG(FALTAS) FROM ALUNOS_DISCIPLINA)
    AND
        (AD.P1 + AD.P2) > (SELECT AVG(AD2.P1 + AD2.P2) FROM ALUNOS_DISCIPLINA AD2)
) AS subquery
GROUP BY 
    subquery.NOME_COMPLETO
ORDER BY 
    DISCIPLINAS_APROVADAS DESC, subquery.NOME_COMPLETO;

