//EXERCICIO 7
SELECT COUNT(id_diciplina) FROM diciplina;

SELECT MIN(NOME) FROM TIPO_DICIPLINA;

SELECT TO_CHAR(MAX(DATA_NACIMENTO),'DD/MM/YYYY') 
	FROM ALUNOS 
		WHERE DATA_NACIMENTO < '01/01/2002';

SELECT ROUND(AVG(FALTAS)),SUM(FALTAS) 
	FROM ALUNOS_DICIPLINA 
		WHERE ID_DICIPLINA = 3;

SELECT COUNT(ID_ALUNOS) 
	FROM ALUNOS 
		WHERE PRIMEIRO_NOME ILIKE '%L%' AND SOBRENOME ILIKE '%A%' AND DATA_NACIMENTO 
			BETWEEN '1992-01-01' AND '2000-01-01';

SELECT 
	COUNT(ID_ALUNO) AS "ALUNOS", 
	MIN(P1) AS "NOTA MINIMA P1", 
	MIN(P2) AS "NOTA MINIMA P2", 
	MAX(FALTAS) AS "MAXIMO DE FALTAS"
FROM ALUNOS_DICIPLINA WHERE ID_DICIPLINA = 6;  

SELECT 
	COUNT(ID_DICIPLINA),
	MIN(P1),MAX(P1),
	MIN(P2),MAX(P2),
	MIN(FALTAS),MAX(FALTAS),
	AVG(P1),AVG(P2),
	AVG(FALTAS),
	SUM(FALTAS)
FROM ALUNOS_DICIPLINA WHERE ID_ALUNO = 4;

SELECT COUNT(ID_ALUNO),MIN(P1),MIN(P2),MAX(FALTAS),AVG(P1),AVG(P2),AVG(FALTAS) 
	FROM ALUNOS_DICIPLINA
		WHERE ID_ALUNO IN (1, 3, 4, 7, 10, 11) 
		AND ID_DICIPLINA IN (2, 4, 5, 6, 8, 9, 15);


//exercicios 8
SELECT NOME FROM DICIPLINA ORDER BY NOME LIMIT 2;

SELECT ID_ALUNO,MIN(P1) FROM ALUNOS_DICIPLINA GROUP BY ID_ALUNO ORDER BY ID_ALUNO;

SELECT tipo_diciplina,COUNT(id_diciplina) FROM DICIPLINA GROUP BY tipo_diciplina ORDER BY tipo_diciplina;

SELECT CONCAT(PRIMEIRO_NOME,' ',SOBRENOME),TO_CHAR(DATA_NACIMENTO,'DD/MM/YYYY') 
	FROM ALUNOS ORDER BY DATA_NACIMENTO LIMIT 5 OFFSET 5;

CREATE VIEW NOME AS SELECT ID_ALUNO,COUNT(ID_DICIPLINA),MAX(P1) AS "P1",MAX(P2),ROUND(AVG(FALTAS::NUMERIC),2)
	FROM ALUNOS_DICIPLINA GROUP BY ID_ALUNO;

SELECT ID_DICIPLINA AS "DICIPLINA",SUM(FALTAS) AS "TOTAL DE FALTAS" 
	FROM alunos_diciplina 
	GROUP BY ID_DICIPLINA HAVING SUM(FALTAS) >= 30 ORDER BY ID_DICIPLINA LIMIT 1 OFFSET 3;

SELECT ID_ALUNO,ID_DICIPLINA,ROUND(P1::NUMERIC + P2::NUMERIC,2) AS "MEDIA" FROM alunos_diciplina 
	WHERE FALTAS <= 10 
	GROUP BY ID_ALUNO,ID_DICIPLINA 
	HAVING AVG(P1 + P2) >= 70;
